package model

const (
	RouteProjects                   = "/api/v1/projects"
	RouteProjectDetail              = "/api/v1/projects/"
	RouteProjectFiles               = "/api/v1/projects/{id}/files"
	RouteFileDownload               = "/api/v1/files/{id}/download"
	RouteFileDownloadByToken          = "/api/v1/files/{token}/download"
	RouteFileSearch                 = "/api/v1/files/search"
	RouteAuthLogin                  = "/api/v1/auth/login"
	RouteAuthRefresh                = "/api/v1/auth/refresh"
	RoutePasswordStatus             = "/api/v1/auth/password-status"
	RouteCrawlStatus                = "/api/v1/crawl/status"
	RouteCrawlTrigger               = "/api/v1/crawl/trigger"
	RouteSystemInfo                 = "/api/v1/system/info"
	RouteOSInstall                  = "/api/v1/os-install/configs"
	RouteCrawlLogs                  = "/api/v1/crawl/logs"
	RouteSystemStats                = "/api/v1/system/stats"
	RouteSystemStatsHistory         = "/api/v1/system/stats/history"
	RouteFileQueue                  = "/api/v1/files/queue"
	RouteFileQueueStats             = "/api/v1/files/queue/stats"
	RouteFileQueueProgress          = "/api/v1/files/queue/progress"
	RouteAdminProjectsList          = "/api/v1/admin/projects"
	RouteAdminProjectsCreate        = "/api/v1/admin/projects"
	RouteAdminProjectsGet           = "/api/v1/admin/projects/{id}"
	RouteAdminProjectsUpdate        = "/api/v1/admin/projects/{id}"
	RouteAdminProjectsDelete        = "/api/v1/admin/projects/{id}"
	RouteAdminProjectsToggle        = "/api/v1/admin/projects/{id}/toggle"
	RouteAdminCrawlTrigger          = "/api/v1/admin/crawl/trigger/{name}"
	RouteAdminCrawlTriggerAll       = "/api/v1/admin/crawl/trigger-all"
	RouteAdminCrawlPause            = "/api/v1/admin/crawl/pause/{name}"
	RouteAdminCrawlResume           = "/api/v1/admin/crawl/resume/{name}"
	RouteAdminCrawlStatus           = "/api/v1/admin/crawl/status"
	RouteAdminCredentialsList       = "/api/v1/admin/credentials"
	RouteAdminCredentialsUpsert     = "/api/v1/admin/credentials"
	RouteAdminPasswordChange        = "/api/v1/admin/password"
	RouteAdminWebDAVStatus          = "/api/v1/admin/webdav/status"
	RouteAdminISODownload           = "/api/v1/admin/os-install/iso/download"
	RouteAdminISOsList              = "/api/v1/admin/os-install/isos"
	RouteAdminISODelete             = "/api/v1/admin/os-install/isos/{name}"
	RouteAdminOSInstallList         = "/api/v1/admin/os-install/configs"
	RouteAdminOSInstallCreate       = "/api/v1/admin/os-install/configs"
	RouteAdminOSInstallUpdate       = "/api/v1/admin/os-install/configs/{id}"
	RouteAdminOSInstallDelete       = "/api/v1/admin/os-install/configs/{id}"
	RouteAdminOSInstallGet          = "/api/v1/admin/os-install/configs/{id}"
	RoutePXEConfig                  = "/pxe/{format}/{name}"
	RouteAdminOSInstallPreview      = "/api/v1/admin/os-install/configs/preview"
	RouteAdminWebDAVList            = "/api/v1/admin/webdav/files"
	RouteAdminISOCatalogList        = "/api/v1/admin/os-install/catalog"
	RouteAdminISOCatalogCreate      = "/api/v1/admin/os-install/catalog"
	RouteAdminISOCatalogUpdate      = "/api/v1/admin/os-install/catalog/{id}"
	RouteAdminISOCatalogDelete      = "/api/v1/admin/os-install/catalog/{id}"
	RouteAdminISOCatalogCheck       = "/api/v1/admin/os-install/catalog/{id}/check"
	RouteAdminISOCatalogDownload    = "/api/v1/admin/os-install/catalog/{id}/download"
	RouteAdminISOCatalogRetry       = "/api/v1/admin/os-install/catalog/{id}/retry"
	RouteAdminISOCatalogCancel      = "/api/v1/admin/os-install/catalog/{id}/cancel"
	RouteAdminISOCatalogCheckAll    = "/api/v1/admin/os-install/catalog/check-all"
	RouteISOsList                   = "/api/v1/isos"
	RouteISODownload                = "/api/v1/isos/{name}/download"
	RouteAdminISOCatalogQueue       = "/api/v1/admin/os-install/catalog/queue"
	RouteAdminISOCatalogDownloadAll = "/api/v1/admin/os-install/catalog/download-all"
	RouteAdminISOCatalogProfiles    = "GET /api/v1/admin/os-install/catalog/profiles"
	RouteAdminDashboardSummary      = "/api/v1/admin/dashboard/summary"
	RouteAdminISOQueueProgress      = "/api/v1/admin/os-install/catalog/progress"
	RouteAdminCacheMetrics       = "/api/v1/admin/metrics/cache"
	// File management (admin)
	// File management (admin)
	RouteAdminFileRetry = "/api/v1/admin/files/{id}/retry"
	RouteFiles = "/api/v1/admin/files"
	RouteFileInternal  = "/api/v1/admin/files/{id}/internal"
	RouteHealth         = "GET /health"
	RouteMetrics        = "GET /metrics"
	// Container management
	RouteAdminContainerList    = "/api/v1/admin/containers"
	RouteAdminContainerCreate  = "/api/v1/admin/containers"
	RouteAdminContainerGet     = "/api/v1/admin/containers/{id}"
	RouteAdminContainerUpdate  = "/api/v1/admin/containers/{id}"
	RouteAdminContainerDelete  = "/api/v1/admin/containers/{id}"
	RouteAdminContainerStart   = "/api/v1/admin/containers/{id}/start"
	RouteAdminContainerStop    = "/api/v1/admin/containers/{id}/stop"
	RouteAdminContainerRestart = "/api/v1/admin/containers/{id}/restart"
	RouteAdminContainerLogs    = "/api/v1/admin/containers/{id}/logs"
	RouteAdminContainerStats   = "/api/v1/admin/containers/{id}/stats"
	// Image management
	RouteAdminImageList   = "/api/v1/admin/images"
	RouteAdminImagePull   = "/api/v1/admin/images/pull"
	RouteAdminImageDelete = "/api/v1/admin/images/{id}"
	// Application templates
	RouteAdminTemplateList   = "/api/v1/admin/templates"
	RouteAdminTemplateCreate = "/api/v1/admin/templates"
	RouteAdminTemplateGet    = "/api/v1/admin/templates/{id}"
	RouteAdminTemplateDelete = "/api/v1/admin/templates/{id}"
	// Logs, Tasks, Search
	RouteAdminLogs   = "/api/v1/admin/logs"
	RouteAdminTasks  = "/api/v1/admin/tasks"
	RouteAdminSearch = "/api/v1/admin/search"
	// Backup management
	RouteAdminBackupList    = "/api/v1/admin/backups"
	RouteAdminBackupRestore = "/api/v1/admin/backups/restore"
	// Monitor config
	RouteAdminConfigMonitor = "/api/v1/admin/config/monitor"
	// Registry management
	RouteRegistryList           = "GET /api/v1/admin/registries"
	RouteRegistryCreate         = "POST /api/v1/admin/registries"
	RouteRegistryGet            = "GET /api/v1/admin/registries/{id}"
	RouteRegistryUpdate         = "PUT /api/v1/admin/registries/{id}"
	RouteRegistryDelete         = "DELETE /api/v1/admin/registries/{id}"
	RouteRegistryTestConnection = "POST /api/v1/admin/registries/test-connection"
	// Registry browsing
	RouteRegistryCatalog   = "GET /api/v1/admin/registries/{id}/catalog"
	RouteRegistryTags      = "GET /api/v1/admin/registries/{id}/tags"
	RouteRegistryTagDetail = "GET /api/v1/admin/registries/{id}/tags/{tag}"
	RouteRegistryTagDelete = "DELETE /api/v1/admin/registries/{id}/tags/{tag}"
	// Sync tasks
	RouteSyncCreate     = "POST /api/v1/admin/sync"
	RouteSyncTaskList   = "GET /api/v1/admin/sync"
	RouteSyncTaskGet    = "GET /api/v1/admin/sync/{id}"
	RouteSyncTaskCancel = "POST /api/v1/admin/sync/{id}/cancel"
	// Retention policies
	RouteRetentionList    = "GET /api/v1/admin/retention"
	RouteRetentionCreate  = "POST /api/v1/admin/retention"
	RouteRetentionUpdate  = "PUT /api/v1/admin/retention/{id}"
	RouteRetentionDelete  = "DELETE /api/v1/admin/retention/{id}"
	RouteRetentionExecute = "POST /api/v1/admin/retention/{id}/execute"
	// Storage config
	RouteStorageConfig        = "/api/v1/admin/config/storage"
	RouteStorageMigrations    = "/api/v1/admin/storage/migrations"
	RouteStorageMigrationByID = "/api/v1/admin/storage/migrations/"
	// Share link management
	RouteShareLinks      = "/api/v1/admin/share-links"
	RouteShareLinkCreate  = "/api/v1/admin/share-links"
	RouteShareLinkRevoke = "/api/v1/admin/share-links/{token}"
	RouteShareDownload   = "GET /s/{token}"
	// Virtual index admin (channels, views, nodes)
	RouteChannels = "/api/v1/admin/channels"
	RouteChannelGet = "/api/v1/admin/channels/{id}"
	RouteViews = "/api/v1/admin/channels/{channel_id}/views"
	RouteViewGet = "/api/v1/admin/views/{id}"
	RouteViewTree = "/api/v1/admin/views/{view_id}/tree"
	RouteNodes = "/api/v1/admin/views/{view_id}/nodes"
	RouteNodeUpdate = "/api/v1/admin/nodes/{id}"
	RouteNodeDelete = "/api/v1/admin/nodes/{id}"
	// Tool catalog
	RouteToolCatalog       = "/api/v1/admin/tool-catalog"
	RouteToolCatalogEnable = "/api/v1/admin/tool-catalog/{slug}/enable"
)