package service

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/Mi-Bee-Studio/mibeehive/internal/model"
)

// Default values for OS install parameters.
const (
	defaultTimezone        = "UTC"
	defaultLanguage        = "en_US"
	defaultKeyboardLayout  = "us"
	defaultDisk            = "/dev/sda"
	defaultPartitionScheme = "whole_disk"
	defaultNetmask         = "255.255.255.0"
)

// ValidationError represents an error caused by invalid user input.
// Handlers should distinguish these from internal errors and return 400.
type ValidationError struct {
	Err error
}

func (e *ValidationError) Error() string {
	return e.Err.Error()
}

func (e *ValidationError) Unwrap() error {
	return e.Err
}


// OsTemplateService generates OS installation configuration files.
type OsTemplateService struct{}

// NewOsTemplateService creates a new OsTemplateService.
func NewOsTemplateService() *OsTemplateService {
	return &OsTemplateService{}
}

// Generate dispatches to the appropriate template generator based on osType.
// Supported osType values: "debian", "ubuntu", "centos", "rhel".
func (s *OsTemplateService) Generate(osType string, params model.OsInstallParams) (string, error) {
	switch strings.ToLower(osType) {
	case "debian":
		return GeneratePreseed(params)
	case "ubuntu":
		return GenerateAutoinstall(params)
	case "centos", "rhel":
		return GenerateKickstart(params, "centos")
	case "rocky", "rockylinux":
		return GenerateKickstart(params, "rocky")
	case "alma", "almalinux":
		return GenerateKickstart(params, "alma")
	case "fedora":
		return GenerateKickstart(params, "fedora")
	case "opensuse", "opensuse-leap":
		return GenerateAutoYAST(params)
	default:
		return "", &ValidationError{Err: fmt.Errorf("unsupported os_type: %q", osType)}
	}
}

// applyDefaults fills in sensible defaults for empty fields.
func applyDefaults(p *model.OsInstallParams) {
	if p.Timezone == "" {
		p.Timezone = defaultTimezone
	}
	if p.Language == "" {
		p.Language = defaultLanguage
	}
	if p.KeyboardLayout == "" {
		p.KeyboardLayout = defaultKeyboardLayout
	}
	if p.Disk == "" {
		p.Disk = defaultDisk
	}
	if p.PartitionScheme == "" {
		p.PartitionScheme = defaultPartitionScheme
	}
	if p.Netmask == "" && p.IPAddress != "" {
		p.Netmask = defaultNetmask
	}
}

// validateParams checks that required fields are present.
func validateParams(p model.OsInstallParams) error {
	if strings.TrimSpace(p.Hostname) == "" {
		return &ValidationError{Err: fmt.Errorf("hostname is required")}
	}
	return nil
}

// isStaticNetwork returns true if an IP address is configured.
func isStaticNetwork(p model.OsInstallParams) bool {
	return strings.TrimSpace(p.IPAddress) != ""
}

// formatDNSServers converts comma-separated DNS servers to a space-separated string.
func formatDNSServers(dns string) string {
	parts := strings.Split(dns, ",")
	var cleaned []string
	for _, s := range parts {
		s = strings.TrimSpace(s)
		if s != "" {
			cleaned = append(cleaned, s)
		}
	}
	return strings.Join(cleaned, " ")
}

// formatPackages converts a package slice to a space-separated string.
func formatPackages(pkgs []string) string {
	return strings.Join(pkgs, " ")
}

// --- Debian Preseed ---

const preseedTemplate = `# Debian Preseed — generated by MiBeeHive
# Locale and keyboard
d-i debian-installer/locale string {{.Language}}
d-i keyboard-configuration/xkb-keymap select {{.KeyboardLayout}}

# Network configuration
{{- if .IsStatic}}
d-i netcfg/disable_autoconfig boolean true
d-i netcfg/get_ipaddress string {{.IPAddress}}
d-i netcfg/get_netmask string {{.Netmask}}
d-i netcfg/get_gateway string {{.Gateway}}
d-i netcfg/get_nameservers string {{.DNSServersFormatted}}
d-i netcfg/confirm_static boolean true
{{- else}}
d-i netcfg/disable_autoconfig boolean false
{{- end}}
d-i netcfg/get_hostname string {{.Hostname}}
d-i netcfg/get_domain string

# Mirror
d-i mirror/country string manual
d-i mirror/http/hostname string deb.debian.org
d-i mirror/http/directory string /debian
d-i mirror/http/proxy string

# Clock and timezone
d-i clock-setup/utc boolean true
d-i time/zone string {{.Timezone}}
d-i clock-setup/ntp boolean true

# Partitioning
{{- if eq .PartitionScheme "whole_disk"}}
d-i partman-auto/method string regular
d-i partman-auto/choose_recipe select atomic
d-i partman-auto/disk string {{.Disk}}
d-i partman/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true
d-i partman/confirm_nooverwrite boolean true
{{- else}}
d-i partman-auto/method string regular
d-i partman-auto/disk string {{.Disk}}
d-i partman/confirm_write_new_label boolean true
d-i partman/confirm boolean true
d-i partman/confirm_nooverwrite boolean true
{{- end}}

# Account setup
{{- if .RootPassword}}
d-i passwd/root-login boolean true
d-i passwd/root-password password {{.RootPassword}}
d-i passwd/root-password-again password {{.RootPassword}}
{{- else}}
d-i passwd/root-login boolean false
{{- end}}
d-i passwd/user-fullname string {{.UserName}}
d-i passwd/username string {{.UserName}}
d-i passwd/user-password password {{.UserPassword}}
d-i passwd/user-password-again password {{.UserPassword}}

# Package selection
tasksel tasksel/first multiselect standard
{{- if .Packages}}
d-i pkgsel/include string {{.PackagesFormatted}}
{{- end}}
d-i pkgsel/update-policy select none
popularity-contest popularity-contest/participate boolean false

# Boot loader
d-i grub-installer/only_debian boolean true
d-i grub-installer/with_other_os boolean true

# Finish
d-i finish-install/reboot_in_progress note

# Late command for SSH key
{{- if .UserSSHKey}}
d-i preseed/late_command string in-target mkdir -p /home/{{.UserName}}/.ssh && in-target chmod 700 /home/{{.UserName}}/.ssh && in-target bash -c 'echo "{{.UserSSHKey}}" > /home/{{.UserName}}/.ssh/authorized_keys' && in-target chown -R {{.UserName}}:{{.UserName}} /home/{{.UserName}}/.ssh && in-target chmod 600 /home/{{.UserName}}/.ssh/authorized_keys
{{- end}}
{{- if .AdditionalConfig}}
# Additional configuration
{{.AdditionalConfig}}
{{- end}}
`

// preseedData holds processed data for the preseed template.
type preseedData struct {
	model.OsInstallParams
	IsStatic           bool
	DNSServersFormatted string
	PackagesFormatted   string
}

// GeneratePreseed generates a Debian preseed configuration file from the given parameters.
func GeneratePreseed(p model.OsInstallParams) (string, error) {
	if err := validateParams(p); err != nil {
		return "", fmt.Errorf("preseed validation: %w", err)
	}
	applyDefaults(&p)

	tmpl, err := template.New("preseed").Parse(preseedTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing preseed template: %w", err)
	}

	data := preseedData{
		OsInstallParams:    p,
		IsStatic:           isStaticNetwork(p),
		DNSServersFormatted: formatDNSServers(p.DNSServers),
		PackagesFormatted:   formatPackages(p.Packages),
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing preseed template: %w", err)
	}
	return buf.String(), nil
}

// --- CentOS/RHEL Kickstart ---

const kickstartTemplate = `# Kickstart — generated by MiBeeHive
# System authorization
auth --useshadow --passalgo=sha512

# Use CDROM or URL installation
{{- if eq .OsType "rocky"}}
url --url=https://download.rockylinux.org/pub/rocky/9/BaseOS/x86_64/os/
{{- else if eq .OsType "alma"}}
url --url=https://repo.almalinux.org/almalinux/9/BaseOS/x86_64/os/
{{- else if eq .OsType "fedora"}}
url --url=https://download.fedoraproject.org/pub/fedora/linux/releases/41/Server/x86_64/os/
{{- else}}
url --url=http://mirror.centos.org/centos/9-stream/BaseOS/x86_64/os/
{{- end}}

# System language and keyboard
lang {{.Language}}
keyboard {{.KeyboardLayout}}

# Network configuration
{{- if .IsStatic}}
network --bootproto=static --ip={{.IPAddress}} --netmask={{.Netmask}} --gateway={{.Gateway}} --nameserver={{.DNSServersFormatted}} --hostname={{.Hostname}} --activate
{{- else}}
network --bootproto=dhcp --hostname={{.Hostname}} --activate
{{- end}}

# Root password
{{- if .RootPassword}}
rootpw --plaintext {{.RootPassword}}
{{- else}}
rootpw lock
{{- end}}

# Timezone
timezone {{.Timezone}} --utc

# Bootloader
bootloader --location=mbr --driveorder={{.Disk}}

# SELinux and firewall
selinux --enforcing
firewall --enabled --ssh

# X Window System
skipx

# Installation
text
reboot

# Disk partitioning
{{- if eq .PartitionScheme "whole_disk"}}
clearpart --all --initlabel --disklabel=gpt
autopart --type=plain
{{- else}}
clearpart --all --initlabel --disklabel=gpt
part /boot --fstype=xfs --size=1024 --ondisk={{.Disk}}
part swap --size=2048 --ondisk={{.Disk}}
part / --fstype=xfs --grow --size=1 --ondisk={{.Disk}}
{{- end}}

# User creation
{{- if .UserName}}
user --name={{.UserName}} --groups=wheel --plaintext --password={{.UserPassword}}
{{- end}}

# Packages
%packages
{{- if .Packages}}
{{range .Packages}}
{{.}}
{{- end}}
{{- else}}
@core
vim
curl
wget
git
{{- end}}
%end

# Post-install script
%post
#!/bin/bash
{{- if .UserSSHKey}}
# Setup SSH key for user
mkdir -p /home/{{.UserName}}/.ssh
chmod 700 /home/{{.UserName}}/.ssh
echo "{{.UserSSHKey}}" > /home/{{.UserName}}/.ssh/authorized_keys
chown -R {{.UserName}}:{{.UserName}} /home/{{.UserName}}/.ssh
chmod 600 /home/{{.UserName}}/.ssh/authorized_keys
{{- end}}
{{- if .AdditionalConfig}}
# Additional configuration
{{.AdditionalConfig}}
{{- end}}
%end
`

// kickstartData holds processed data for the kickstart template.
type kickstartData struct {
	model.OsInstallParams
	IsStatic            bool
	DNSServersFormatted string
	OsType              string
}

// GenerateKickstart generates a kickstart configuration file for the given OS type.
func GenerateKickstart(p model.OsInstallParams, osType string) (string, error) {
	if err := validateParams(p); err != nil {
		return "", fmt.Errorf("kickstart validation: %w", err)
	}
	applyDefaults(&p)

	tmpl, err := template.New("kickstart").Parse(kickstartTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing kickstart template: %w", err)
	}

	data := kickstartData{
		OsInstallParams:    p,
		IsStatic:           isStaticNetwork(p),
		DNSServersFormatted: formatDNSServers(p.DNSServers),
		OsType:             osType,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing kickstart template: %w", err)
	}
	return buf.String(), nil
}

// --- Ubuntu Autoinstall (20.04+) ---

const autoinstallTemplate = `#cloud-config
# Ubuntu Autoinstall — generated by MiBeeHive
version: 1

identity:
  hostname: {{.Hostname}}
  realname: {{.UserName}}
  username: {{.UserName}}
  password: "{{.UserPassword}}"

{{- if .IsStatic}}
network:
  version: 2
  ethernets:
    eth0:
      addresses:
        - {{.IPAddress}}/{{.NetmaskCIDR}}
      gateway4: {{.Gateway}}
      nameservers:
        addresses:
{{- range .DNSServersList}}
          - {{.}}
{{- end}}
{{- else}}
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: true
{{- end}}

locale: {{.Language}}
keyboard:
  layout: {{.KeyboardLayout}}
  variant: ''

timezone: {{.Timezone}}

ssh:
  install-server: true
{{- if .UserSSHKey}}
  authorized-keys:
    - "{{.UserSSHKey}}"
{{- end}}

storage:
  layout:
{{- if eq .PartitionScheme "whole_disk"}}
    name: direct
{{- else}}
    name: lvm
{{- end}}

{{- if .Packages}}
packages:
{{- range .Packages}}
  - {{.}}
{{- end}}
{{- end}}

{{- if .AdditionalConfig}}
# Additional configuration
{{.AdditionalConfig}}
{{- end}}

# Late commands
late-commands:
{{- if .UserSSHKey}}
  - "echo '{{.UserSSHKey}}' >> /target/home/{{.UserName}}/.ssh/authorized_keys"
  - "chown -R {{.UserName}}:{{.UserName}} /target/home/{{.UserName}}/.ssh"
  - "chmod 700 /target/home/{{.UserName}}/.ssh"
  - "chmod 600 /target/home/{{.UserName}}/.ssh/authorized_keys"
{{- end}}
  - "echo 'Installation complete' > /target/var/log/install-complete"
`

// autoinstallData holds processed data for the autoinstall template.
type autoinstallData struct {
	model.OsInstallParams
	IsStatic      bool
	NetmaskCIDR   string
	DNSServersList []string
}

// GenerateAutoinstall generates an Ubuntu 20.04+ autoinstall YAML configuration file.
func GenerateAutoinstall(p model.OsInstallParams) (string, error) {
	if err := validateParams(p); err != nil {
		return "", fmt.Errorf("autoinstall validation: %w", err)
	}
	applyDefaults(&p)

	tmpl, err := template.New("autoinstall").Parse(autoinstallTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing autoinstall template: %w", err)
	}

	// Convert netmask to CIDR notation.
	netmaskCIDR := "24"
	if p.Netmask != "" {
		netmaskCIDR = netmaskToCIDR(p.Netmask)
	}

	// Parse DNS servers into a list.
	var dnsList []string
	if p.DNSServers != "" {
		parts := strings.Split(p.DNSServers, ",")
		for _, s := range parts {
			s = strings.TrimSpace(s)
			if s != "" {
				dnsList = append(dnsList, s)
			}
		}
	}

	data := autoinstallData{
		OsInstallParams:  p,
		IsStatic:         isStaticNetwork(p),
		NetmaskCIDR:      netmaskCIDR,
		DNSServersList:   dnsList,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing autoinstall template: %w", err)
	}
	return buf.String(), nil
}

// netmaskToCIDR converts a netmask like "255.255.255.0" to CIDR prefix like "24".
func netmaskToCIDR(mask string) string {
	bits := strings.Split(mask, ".")
	if len(bits) != 4 {
		return "24"
	}
	var cidr int
	for _, octet := range bits {
		val := 0
		for _, ch := range octet {
			val = val*10 + int(ch-'0')
		}
		cidr += countBits(val)
	}
	return fmt.Sprintf("%d", cidr)
}

// countBits counts the number of set bits in an integer.
func countBits(n int) int {
	count := 0
	for n > 0 {
		count += n & 1
		n >>= 1
	}
	return count
}
