package service

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/Mi-Bee-Studio/mibeehive/internal/model"
)

// --- openSUSE AutoYAST ---

const autoYASTTemplate = `<?xml version="1.0"?>
<!-- AutoYAST Profile — generated by MiBeeHive -->
<!DOCTYPE profile SYSTEM "/usr/share/autoinstall/dtd/profile.dtd">
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
  <general>
    <mode>
      <confirm config:type="boolean">false</confirm>
    </mode>
  </general>
  <language>{{.Language}}</language>
  <keyboard>
    <keymap>{{.KeyboardLayout}}</keymap>
  </keyboard>
  <timezone>{{.Timezone}}</timezone>
  <networking>
    <interfaces config:type="list">
      <interface>
        <bootproto>{{if .IsStatic}}static{{else}}dhcp{{end}}</bootproto>
        <device>eth0</device>
        {{- if .IsStatic}}
        <ipaddr>{{.IPAddress}}</ipaddr>
        <netmask>{{.Netmask}}</netmask>
        {{- end}}
        <startmode>auto</startmode>
      </interface>
    </interfaces>
    {{- if .IsStatic}}
    <dns>
      <hostname>{{.Hostname}}</hostname>
      <nameservers config:type="list">
        {{- range .DNSServersList}}
        <nameserver>{{.}}</nameserver>
        {{- end}}
      </nameservers>
    </dns>
    <routing>
      <routes config:type="list">
        <route>
          <destination>default</destination>
          <gateway>{{.Gateway}}</gateway>
        </route>
      </routes>
    </routing>
    {{- end}}
  </networking>
  <partitioning config:type="list">
    <drive>
      <device>{{.Disk}}</device>
      <use>all</use>
    </drive>
  </partitioning>
  <users config:type="list">
    {{- if .RootPassword}}
    <user>
      <username>root</username>
      <user_password>{{.RootPassword}}</user_password>
      <encrypted config:type="boolean">false</encrypted>
    </user>
    {{- end}}
    {{- if .UserName}}
    <user>
      <username>{{.UserName}}</username>
      <user_password>{{.UserPassword}}</user_password>
      <encrypted config:type="boolean">false</encrypted>
      <home>/home/{{.UserName}}</home>
    </user>
    {{- end}}
  </users>
  <software>
    <patterns config:type="list">
      <pattern>base</pattern>
    </patterns>
    {{- if .Packages}}
    <packages config:type="list">
      {{- range .Packages}}
      <package>{{.}}</package>
      {{- end}}
    </packages>
    {{- end}}
  </software>
  {{- if .UserSSHKey}}
  <scripts>
    <post-scripts config:type="list">
      <script>
        <filename>setup-ssh.sh</filename>
        <interpreter>shell</interpreter>
        <source><![CDATA[#!/bin/bash
mkdir -p /home/{{.UserName}}/.ssh
chmod 700 /home/{{.UserName}}/.ssh
echo "{{.UserSSHKey}}" > /home/{{.UserName}}/.ssh/authorized_keys
chown -R {{.UserName}}:users /home/{{.UserName}}/.ssh
chmod 600 /home/{{.UserName}}/.ssh/authorized_keys
]]></source>
      </script>
    </post-scripts>
  </scripts>
  {{- end}}
</profile>`

// autoYASTData holds processed data for the AutoYAST template.
type autoYASTData struct {
	model.OsInstallParams
	IsStatic       bool
	DNSServersList []string
}

// GenerateAutoYAST generates an openSUSE AutoYAST XML configuration file.
func GenerateAutoYAST(p model.OsInstallParams) (string, error) {
	if err := validateParams(p); err != nil {
		return "", fmt.Errorf("autoyast validation: %w", err)
	}
	applyDefaults(&p)

	tmpl, err := template.New("autoyast").Parse(autoYASTTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing autoyast template: %w", err)
	}

	// Parse DNS servers into a list.
	var dnsList []string
	if p.DNSServers != "" {
		parts := strings.Split(p.DNSServers, ",")
		for _, s := range parts {
			s = strings.TrimSpace(s)
			if s != "" {
				dnsList = append(dnsList, s)
			}
		}
	}

	data := autoYASTData{
		OsInstallParams: p,
		IsStatic:        isStaticNetwork(p),
		DNSServersList:  dnsList,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing autoyast template: %w", err)
	}
	return buf.String(), nil
}
